[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
gifportal = "5tzyMy3NYB8C93QircdAPEf1QP7GDFWRZ9K8D6imbivx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/roster/.config/solana/devnet.json"

[scripts]
test = "node ./tests/gifportal.js"
